import { readFile } from "node:fs/promises";

interface Config {owner:string;repo:string;branch:string;token:string;fetchImpl?:typeof fetch;}
interface Ref {object:{sha:string}} interface Commit {sha:string;tree:{sha:string}} interface Blob {content:string;encoding:string} interface Sha {sha:string}
class GitHubInboxHttpError extends Error { constructor(readonly status:number, body:string){super(`GITHUB_INBOX_HTTP_${status}:${body.slice(0,200)}`);} }
export class GitHubInboxTransport {
 private f:typeof fetch;
 constructor(private c:Config){this.f=c.fetchImpl??fetch;}
 private async req<T>(path:string,init:RequestInit={}):Promise<T>{const r=await this.f(`https://api.github.com/repos/${this.c.owner}/${this.c.repo}${path}`,{...init,headers:{"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Authorization":"Bearer "+this.c.token,"User-Agent":"revenue-automaton",...(init.headers??{})}});if(!r.ok)throw new GitHubInboxHttpError(r.status,await r.text());return await r.json() as T;}
 async read():Promise<{version:string;content:string|undefined}>{const ref=await this.req<Ref>(`/git/ref/heads/${encodeURIComponent(this.c.branch)}`);const commit=await this.req<Commit>(`/git/commits/${ref.object.sha}`);const tree=await this.req<any>(`/git/trees/${commit.tree.sha}?recursive=1`);const entry=tree.tree.find((x:any)=>x.path==="opportunity-inbox.json"&&x.type==="blob");if(!entry)return {version:ref.object.sha,content:undefined};const blob=await this.req<Blob>(`/git/blobs/${entry.sha}`);return {version:ref.object.sha,content:Buffer.from(blob.content.replace(/\n/g,""),"base64").toString("utf8")};}
 async commit(expected:string,content:string):Promise<string>{const now=await this.read();if(now.version!==expected)throw new Error("INBOX_STALE");const commit=await this.req<Commit>(`/git/commits/${expected}`);const blob=await this.req<Sha>("/git/blobs",{method:"POST",body:JSON.stringify({content,encoding:"utf-8"})});const tree=await this.req<Sha>("/git/trees",{method:"POST",body:JSON.stringify({base_tree:commit.tree.sha,tree:[{path:"opportunity-inbox.json",mode:"100644",type:"blob",sha:blob.sha}]})});const next=await this.req<Sha>("/git/commits",{method:"POST",body:JSON.stringify({message:"opportunity inbox: update",tree:tree.sha,parents:[expected]})});try{await this.req(`/git/refs/heads/${encodeURIComponent(this.c.branch)}`,{method:"PATCH",body:JSON.stringify({sha:next.sha,force:false})});}catch(e){if(e instanceof GitHubInboxHttpError&&(e.status===409||e.status===422))throw new Error("INBOX_STALE");throw e;}return next.sha;}
}
export async function updateInboxBranch(discoveryPath:string,c:Config):Promise<void>{const transport=new GitHubInboxTransport(c);for(let attempt=0;attempt<3;attempt++){const view=await transport.read();if(view.content)await import("node:fs/promises").then(fs=>fs.writeFile("opportunity-inbox.json",view.content!));else await import("node:fs/promises").then(fs=>fs.rm("opportunity-inbox.json",{force:true}));const {spawnSync}=await import("node:child_process");const run=spawnSync(process.execPath,["dist/opportunity-inbox-cli.js",discoveryPath,"opportunity-inbox.json"],{stdio:"inherit"});if(run.status!==0)throw new Error("INBOX_BUILD_FAILED");const content=await readFile("opportunity-inbox.json","utf8");try{await transport.commit(view.version,content);return;}catch(e){if((e as Error).message!=="INBOX_STALE"||attempt===2)throw e;}}}
